
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from 'sonner';

const SUPABASE_URL = "https://gibsyygowtzieicrnqyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpYnN5eWdvd3R6aWVpY3JucXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODQ3OTMsImV4cCI6MjA2MzE2MDc5M30.gBG1diWhnz9cGFJwh-vSQgRd9Gzbu5nUu69C8TU5jWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'Content-Type': 'application/json',
      },
    },
    db: {
      schema: 'public',
    },
    // Ajout de la configuration pour améliorer la stabilité des connexions
    realtime: {
      timeout: 60000, // Augmentation du timeout
    }
  }
);

// Fonction utilitaire pour vérifier la connexion à Supabase avec plus de détails
export const checkSupabaseConnection = async () => {
  console.log("Tentative de connexion à Supabase...");
  try {
    const { data, error } = await supabase.from('registrations').select('count').limit(1);
    
    if (error) {
      console.error("Erreur de connexion à Supabase:", error);
      console.error("Code d'erreur:", error.code);
      console.error("Message d'erreur:", error.message);
      console.error("Détails:", error.details);
      
      // Notification pour l'utilisateur
      toast.error(`Erreur de connexion à la base de données: ${error.message}`);
      return false;
    }
    
    console.log("Connexion à Supabase établie avec succès", data);
    return true;
  } catch (e) {
    console.error("Exception lors de la tentative de connexion à Supabase:", e);
    if (e instanceof Error) {
      console.error("Message d'erreur:", e.message);
      console.error("Stack trace:", e.stack);
      
      // Notification pour l'utilisateur
      toast.error(`Exception lors de la connexion à la base de données: ${e.message}`);
    }
    return false;
  }
};

// Fonction utilitaire pour tester la capacité à insérer des données
export const testSupabaseInsert = async () => {
  try {
    const testData = {
      first_name: "Test",
      last_name: "Connection",
      email: `test-${Date.now()}@example.com`,
      phone: "0000000000",
      university: "Test University",
      major: "Test Major",
      graduation_year: "2025",
      skills: ["test"],
      track: "open",
      experience: "Test",
      team_preference: "solo"
    };
    
    console.log("Tentative d'insertion de données de test dans Supabase...", testData);
    
    const { data, error } = await supabase
      .from('registrations')
      .insert([testData])
      .select();
    
    if (error) {
      console.error("Erreur lors de l'insertion de test dans Supabase:", error);
      return false;
    }
    
    console.log("Insertion de test réussie dans Supabase:", data);
    return true;
  } catch (e) {
    console.error("Exception lors du test d'insertion dans Supabase:", e);
    return false;
  }
};

